search_config.settings:
	type: config_object
	mapping:
		basic:
			type: string
			label: 'Enter your keywords'
		basic_with_keys:
			type: string
			label: 'Enter your keywords'
		basic_submit:
			type: string
			label: 'Search'
		advanced_fieldset:
			type: string
			label: 'Advanced search'
		advanced_fieldset_with_keys:
			type: string
			label: 'Advanced search'
		advanced_any:
			type: string
			label: 'Contaiining any of the words'
		advanced_phrase:
			type: string
			label: 'Containing the phrase'
		advanced_none:
			type: string
			label: 'Containing none of the words'
		advanced_type:
			type: string
			label: 'Only of the type(s)'
		advanced_language:
			type: string
			label: 'Languages'
		advanced_submit:
			type: string
			label: 'Advanced search'

